server:
    port: 9090
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: admin
        url: jdbc:postgresql://localhost:5432/saham_book?createDatabaseIfNotExist=true
        username: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
